# Generated by Django 5.0.7 on 2024-08-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
    ]
